spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port : 5555
  
eureka:
  instance:
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
      
zuul:
  routes:
    userservice: /user/**
    itemservice: /item/**
  ignored-services: '*'
  prefix: /api
      